Added optical spectra from refractiveindex.info as composite features
Matgenix/matminer pull request #1
Opened 2022-06-28 13:12 UTC by gbrunin

## Summary

The idea is to add the optical features based on data from https://www.refractiveindex.info
I first extracted the (relevant*) data, then created 2 sets of 3 tables (refractive index, extinction coefficient, reflectivity). 
The 2 sets correspond to 1) the pure elements, as averaged over available data from different sources (if any), 
and 2), the pseudo-inverse values for each element (corresponding to the least-square fit), based on ~200 data points. 
The second solution (based on the pseudo-inverse) leads to better results when compared to exact ones from the database 
and is chosen as the default.

*Relevant in the sense that I included only solid-state non-organic materials, and only took the data if the spectrum from 380 to 780 nm was covered.

I also include the transport properties in the same way (pure elements or based on their pseudo-inverses). These come from the database of transport properties computed by Ricci et al (2017) that can be retrieved from the Materials Project.

## TODO

2022-06-30 11:11 UTC, gbrunin commented on matminer/featurizers/composition/composite.py
> +class RefractiveIndex(ElementProperty):
We either use this as is, and remove the changes in ElementProperty, or keep the changes in ElementProperty and remove this. What do you think ?

2022-08-26 13:12 UTC, davidwaroquiers requested changes
Great work!
I did some comments with suggestions. We can look through it together if you want when you come back.

2022-08-26 13:12 UTC, davidwaroquiers commented on matminer/utils/data.py
> +                                raise Warning('Material of unknown type: ' + material)
I would maybe document somewhere the procedure to add some new data file.

2022-08-26 13:12 UTC, davidwaroquiers commented on matminer/utils/data.py
> +                if data_format == 'formula 1':
Maybe this could be put outside this method so that we can use it directly ? Not sure if it is important though.

2022-08-26 13:12 UTC, davidwaroquiers commented on matminer/utils/io.py
> +    elements = ['H', 'He',
Maybe construct it from pymatgen ?

2022-08-26 13:12 UTC, davidwaroquiers commented on matminer/utils/io.py
> +                if elem in compound and elem not in elems_in_df:
You could use sets instead of lists here so that you just do

```
if element in compound:
    elems_in_df.add(element)
```

Then return the list at the end if a list expected (but I would say an iterable is sufficient, so maybe the set can be returned).

2022-08-26 13:13 UTC, davidwaroquiers commented
Also, I did not say here but we may need to modify some things so that the amount of data is not too large, when we request to merge to the main matminer. We will see what they say about that.

2022-08-26 14:17 UTC, davidwaroquiers commented on matminer/utils/data.py
> +        # Compute the pseudo-inversed values
Here is the part that I would maybe consider extracting in OpticalData:

```
elems_in_df, elems_not_in_df = get_elem_in_data(data, as_pure=False)
n_elem_tot = len(elems_in_df)

# Initialize the matrix
A = np.zeros([len(self.data), n_elem_tot])

compos = self.data['Composition']
for i, comp in enumerate(compos):
    comp = Composition(comp)
    for j in range(n_elem_tot):
        if elems_in_df[j] in comp:
            A[i, j] = comp.get_atomic_fraction(elems_in_df[j])

pi_A = pinv(A)

res_pi = pi_A @ data.values
res_pi = np.vstack([res_pi, np.nan * np.ones([len(elems_not_in_df), len(self.props) * self.n_wl])])

df_pi = pd.DataFrame(res_pi, columns=cols, index=pd.Index(elems_in_df + elems_not_in_df))
```


And here is the corresponding in TransportData:

```
elems_in_df, elems_not_in_df = get_elem_in_data(TP, as_pure=False)
n_elem_tot = len(elems_in_df)

# Initialize the matrix
A = np.zeros([len(TP), n_elem_tot])

compos = TP.index
for i, comp in enumerate(compos):
    comp = Composition(comp)
    for j in range(n_elem_tot):
        if elems_in_df[j] in comp:
            A[i, j] = comp.get_atomic_fraction(elems_in_df[j])

pi_A = pinv(A)

TP_pi = pi_A @ TP.values
TP_pi = np.vstack([TP_pi, np.nan * np.ones([len(elems_not_in_df), len(TP.T)])])

df_pi = pd.DataFrame(TP_pi, columns=TP.columns, index=pd.Index(elems_in_df + elems_not_in_df))
```

2022-09-01 13:32 UTC, gpetretto reviewed
Thanks for all the work!
I added some comments and questions.

Some general remarks:
- if the stored files are too large it could be an option to compress them? Also switching to some other format other than csv may be an option, but I am not sure if this will introduce unwanted dependencies in matminer
- in case you did not do already, before opening the PR to the trunk it would be good to set up the pre-commit, so you will get the linting erros checked beforehand.

2022-09-01 13:32 UTC, gpetretto commented on matminer/utils/io.py
> +    elements = ['H', 'He',
actually you can even remove this and do
```python
from pymatgen.core import Element

for elem in Element:
    if elem.name in df.index:
        ...
```

2022-09-01 13:32 UTC, gpetretto commented on matminer/utils/io.py
> +def get_elem_in_data(df, as_pure=False):
this function is not tested

2022-09-06 12:50 UTC, gbrunin commented on matminer/utils/data.py
> +        db_dir = [os.path.join(module_dir, "data_files/optical_polyanskiy/database/other/semiconductor alloys/"),
I know and I don't like it either :p I simply took the structure from the database itself (https://github.com/polyanskiy/refractiveindex.info-database/tree/master/database/data).
I have made modifications on some files from the database though (to make them consistent), so I have nothing against changing the structure to make it easier in matminer (it's just something I was avoiding because it's boring, but I can do it). This could also simplify the code for the reading of the data with the conditions in the dir.

2022-09-06 12:54 UTC, gbrunin commented on matminer/utils/data.py
> +        self.elem_data = self._get_element_props()
I have precomputed it for a given set of wavelengths, but if anyone wants to choose other wavelengths then the database needs to be browsed again. Indeed not all materials in the database have available data for the same range of wavelengths, so I have to check for each of them and that depends on the wanted wavelengths. It's also not that long to recompute (and might even be faster if I format a little bit the database to make things simpler).

2022-09-06 13:38 UTC, gbrunin commented on matminer/utils/data.py
> +        cols_names_n = ['n_{0}'.format(np.round(wl, 2)) for wl in W]
Mmmh, I don't think it would be a problem, unless someone needs the spectra on a super fine grid, but that would not make much sense in a ML framework. I set it to 2 digits so that we still have easily a physical sense when we see the feature label, which will be something like R_670.43 if we use a weird number of wavelengths. This avoids having R_670.4346754325. I think I'll keep it like that for now

2022-09-06 13:46 UTC, gbrunin commented on matminer/featurizers/composition/composite.py
> +        stats = ["minimum", "maximum", "range", "mean", "std_dev", "mode"]
I have added the features and stats as arguments of the init. 
@gpetretto I initially added the features as part of the ElementProperty class, using the from_preset method. The problem I faced was that I had to pass different arguments depending on the property (like the number of wavelengths for optical data, but not for transport), and it was starting to look like a mess so I decided to make them subclasses. What would the from_preset look like in the current scenario ? Basically the same as the init ? The thing is that I do not see a use case for the from_preset function here, so maybe instead we should just have it do nothing or raise a warning ?

2022-09-06 14:45 UTC, gpetretto commented on matminer/featurizers/composition/composite.py
> +        stats = ["minimum", "maximum", "range", "mean", "std_dev", "mode"]
The point is that that both the `__init__` and `from_preset` method do not really need to expose all the inputs options. The PymatgenData has one option in input, but this is not exposed anywhere of course: https://github.com/hackingmaterials/matminer/blob/main/matminer/utils/data.py#L229

The preset can (should?) provide _both_ the generic properties like `stats` and all the values specific to your case. If a user wants to specify all the values (which is probably not very likely) he still has the simple solution of instantiating an OpticalData object.
 
In addition, if you check the original `ElementProperty`, no attribute is set in the __init__. There are not even defaults: https://github.com/hackingmaterials/matminer/blob/main/matminer/featurizers/composition/composite.py#L48 and all the setting is delagated to the `from_preset`

So, one example of minimalistic implementation could be like this:
```python
class ElementProperty(BaseFeaturizer):
    """
       ...
    """

    def __init__(self, data_source, features, stats):
        if data_source == "pymatgen":
            self.data_source = PymatgenData()
        elif data_source == "magpie":
            self.data_source = MagpieData()
        elif data_source == "deml":
            self.data_source = DemlData()
        elif data_source == "matscholar_el":
            self.data_source = MatscholarElementData()
        elif data_source == "megnet_el":
            self.data_source = MEGNetElementData()
        elif data_source == "optical":
            self.data_source = OpticalData(()
        else:
            self.data_source = data_source

        self.features = features
        self.stats = stats
        # Initialize stats computer
        self.pstats = PropertyStats()

    @classmethod
    def from_preset(cls, preset_name):
        """
           ...
        """
        if preset_name == "magpie":
            ...
        elif preset_name == "optical":
            data_source = OpticalData()
            features = data_source.prop_names
            stats = ["minimum", "maximum", "range", "mean", "std_dev", "mode"]
        else:
            raise ValueError("Invalid preset_name specified!")

        return cls(data_source, features, stats)            
```

If you think it is preferable that this has its own object, bacause it does not fit well with the other ElementProperty, you can do something similar to the `CationProperty`, https://github.com/hackingmaterials/matminer/blob/main/matminer/featurizers/composition/ion.py#L15

```python
class RefractiveIndex(ElementProperty):
    """
       ...
    """

    @classmethod
    def from_preset(cls, preset_name):
        """
           ...
        """
        if preset_name == "optical":
            data_source = OpticalData()
            features = data_source.prop_names
            stats = ["minimum", "maximum", "range", "mean", "std_dev", "mode"]
        else:
            raise ValueError("Invalid preset_name specified!")

        return cls(data_source, features, stats)            
```
Notice that here you don't even need to define the `__init__`.

I don't see these solutions as offering any less options for customisation to the user and actually they avoid the annoying problem of having defined the defaults for all your input variables (`min_wl`, `max_wl`, ...) in two different places, i.e. the `RefractiveIndex` and the `OpticalData`. If by any chance one value gets updated it would make sense to do it in both places, but it is not obvious that the person who does the upate knows or remembers to do that. 

If you feel like that the inputs should still go in the `__init__`, even though this basically breaks the signature of the method, I would still advise to go for something like this:

```python
class RefractiveIndex(ElementProperty):
    """
       ...
    """

    def __init__(self, features, stats, method, props, bins, min_wl, max_wl, n_wl):
        data_source = OpticalData(method=method, props=props, bins=bins, min_wl=min_wl,
                                  max_wl=max_wl, n_wl=n_wl)
        super().__init__(data_source, features, stats)

    @classmethod
    def from_preset(cls, preset_name):
        """
           ...
        """
        if preset_name == "optical":
            method='pseudo_inverse'
            props=None
            bins=10
            min_wl=0.38
            max_wl=0.78
            n_wl=401
            data_source = OpticalData(method=method, props=props, bins=bins, min_wl=min_wl,
                                  max_wl=max_wl, n_wl=n_wl)
            features = data_source.prop_names
            stats = ["minimum", "maximum", "range", "mean", "std_dev", "mode"]
            return cls(features, stats, method=method, props=props, bins=bins, min_wl=min_wl,
                                  max_wl=max_wl, n_wl=n_wl)      
        else:
            raise ValueError("Invalid preset_name specified!")
```

Actually, this could also be a case where you might think of implementing the `RefractiveIndex` with _has-a_ relation with `ElementProperty` rather than a _is-a_.

In the end I would probably go for the second of the options I have listed above. Maybe @davidwaroquiers  can also comment on this.

2022-09-06 14:50 UTC, gpetretto commented on matminer/utils/data.py
> +        cols_names_n = ['n_{0}'.format(np.round(wl, 2)) for wl in W]
I agree. It was just that I do not have a feeling of the typical numbers you get there. It is fine like this then.

2022-09-07 09:47 UTC, gbrunin commented on matminer/utils/data.py
> +                if data_format == 'formula 1':
I know it is a bit ugly because of the different formats of the data files, but I don't think it will be used elsewhere so I think we can leave them there

2022-09-07 09:48 UTC, gbrunin commented on matminer/featurizers/composition/composite.py
> +              of elemental features for each property.
Yes exactly. I guess the descriptions are not clear enough, I'll work on that

2022-10-07 15:46 UTC, gpetretto reviewed
Thanks for the updates. I have added some more comments.

2022-11-17 15:20 UTC, davidwaroquiers commented on matminer/utils/data.py
> +            print("Selecting non-default wavelengths: recollecting the data from the database...")
Ok I would suggest removing it then.

2022-11-17 15:24 UTC, davidwaroquiers commented on matminer/utils/data.py
> +                if data_format == 'formula 1':
Ok let's keep it like this for now.

2022-11-18 09:14 UTC, merged